version: "3"

services:
  web:
    build: ./web
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - "443:443"
      - "80:80"

  jenkins:
    build: ./jenkins
    networks:
      - backend
    restart: always
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/libexec/docker/bin/docker
      - jenkins-data:/var/lib/jenkins/
    environment:
      - JENKINS_ADMIN_USER=admin
      - JENKINS_ADMIN_PASSWORD=admin123

  sonarqube:
    build: ./sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
    networks:
      - backend
  sonarqube-db:
    build: ./sonarqube-db
    networks:
      - backend
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
      - sonarqube-db:/var/lib/postgresql

  nexus:
    build: ./nexus
    networks:
      - backend
    volumes:
      - nexus-data:/nexus-data

volumes:
  jenkins-data:
  sonarqube-data:
  sonarqube-conf:
  sonarqube-db-data:
  sonarqube-db:
  nexus-data:

networks:
  frontend:
  backend:
